### ISSUE TITLE
NameError: global name 'tone' is not defined

### ISSUE THREAD

**Issue by sm3ulc** [rtmrtmrtmrtm/weakmon#2]
Got error when running:

python2.7 jt65mon.py -card sdrplay sdrplay -v -band 40
sdrplay: loaded API from libmirsdrapi-rsp.so
sdrplay.py: warning: needs API version 1.95, got 2.090000
reporting to pskreporter as xxxx at yyyyy
band 40 ;
samples <type 'numpy.float64'>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "jt65mon.py", line 331, in <lambda>
    th = threading.Thread(target=lambda : r.gocard())
  File "/home/davidl/workspace/weakmon/jt65.py", line 247, in gocard
    self.process(samples[i0:], t)
  File "/home/davidl/workspace/weakmon/jt65.py", line 293, in process
    self.process0(samples, samples_time, thunk, 0, 2580)
  File "/home/davidl/workspace/weakmon/jt65.py", line 515, in process0
    dec = self.process1(samples, hz, noise, scores[i][3], already)
  File "/home/davidl/workspace/weakmon/jt65.py", line 731, in process1
    dec = self.process1a(samples, xhz, start, noise, already)
  File "/home/davidl/workspace/weakmon/jt65.py", line 770, in process1a
    a = weakutil.fft_of_shift(block, -freq_off, self.jrate)
  File "/home/davidl/workspace/weakmon/weakutil.py", line 174, in fft_of_shift
    lo = tone(rate, hz, len(a))
NameError: global name 'tone' is not defined

**Comment by rtmrtmrtmrtm** [comment]
I fixed the tone() error -- thank you for pointing this out.

Robert
